[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci --only=production"]

[phases.build]
cmds = ["npx prisma generate"]

[start]
cmd = "npx prisma migrate deploy && node src/index.js"
